# MIT License
# Copyright (C) 2020 Tymko Oleg <olegtymko@yandex.ru> and contributors
# All rights reserved.

name: Подготовка релиза и публикация в хабе
# Только события создания и изменения релиза
on:
    release:
        types: [published, edited]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        oscript_version: ['default']
        package_mask: ["gitsync-*.ospx"]
    steps:
      # Загрузка проекта
      - name: Актуализация
        uses: actions/checkout@v4.2.2

      # Установка OneScript конкретной версии
      - name: Установка OneScript
        uses: otymko/setup-onescript@v1.5
        with:
          version: ${{ matrix.oscript_version }}

      # Установка зависимостей пакета
      - name: Установка зависимостей
        run: |
          opm install opm
          opm install

      - name: Сборка пакета
        run: opm run build

      - name: Заливка артефактов
        uses: actions/upload-artifact@v6.0.0
        with:
          name: gitsync.ospx.zip
          path: ./${{ matrix.package_mask }}

      - name: Заливка в релиз
        uses: AButler/upload-release-assets@v3.0.1
        with:
          files: ./${{ matrix.package_mask }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Публикация в hub.oscript.io
        shell: bash
        run: opm push -f ./${{ matrix.package_mask }} --token ${{ env.TOKEN }} -c stable
        env:
          TOKEN: ${{ secrets.ACCESS_TOKEN }}
